#LIBRERIA OPENCV
import cv2 as cv
import numpy as np

#METODO APRA LEER IMAGENES / REGRESA UNA MATRIZ DE PIXELES DE LA IMAGEN
img = cv.imread('Photos/imagen2.jpg')
#METODO PARA MOSTRAR IMAGENES, PARAMETROS( NOMBRE_DE_VENTANA, IMAGEN) 

cv.imshow('Cat',img)
#ESTA FUNCION SE USA PARA HACER QUE EL PROGRAMA ESPERE
#INDEFINIDAMENTE A QUE EL USUARIO PRESIONE UNA TECLA, APRA DETENER LA EJECUCION
#EL VALOR DEL PARAMETRO ES EL TIEMPO EN MILISEGUNDOS, PERO EL 0 ES INFINITO
cv.waitKey(0)
