#LIBRERIA OPENCV
import cv2 as cv
import numpy as np

#PARA LEER UN VIDEO SE USARA EL METODO VIDEOCAPTURE
#ESTE PUEDE SUAR ARGUMENTOS ENTEROS, PERO ESTOS AHRAN REFERENCIA
#A LA WEB CAM U OTRO DISPOSITIVO DE VIDEO QUE TENGAMOS
#EN EL CASO DE LEER UN VIDEO EN ESPECIFICO USAREMOS SU RUTA
capture = cv.VideoCapture(0)

#LA MANERA DE LEER UN VIDEO ES FRAME X FRAME EN UN LOOP

while True:
    #LA FUNCION RETORNA EL FRAME Y UN BOOLEANO 
    #PARA SABER SI EL FRAME HA PODIDO LEERSE CORRECTAMENTE
    isTrue,frame = capture.read()
    cv.imshow('Video',frame)

    if cv.waitKey(20) & 0xFF==ord('d'):
        break

capture.release()
cv.destroyAllWindows()
